Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# --- Aufruf der Extraktion ---
pdf_folder = "..."  # TODO: Gib den Ordnerpfad mit den PDFs an
raw_text = extract_text_from_pdf_folder(pdf_folder)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[5], line 3[0m
[1;32m      1[0m [38;5;66;03m# --- Aufruf der Extraktion ---[39;00m
[1;32m      2[0m pdf_folder [38;5;241m=[39m [38;5;124m"[39m[38;5;124m...[39m[38;5;124m"[39m  [38;5;66;03m# TODO: Gib den Ordnerpfad mit den PDFs an[39;00m
[0;32m----> 3[0m raw_text [38;5;241m=[39m [43mextract_text_from_pdf_folder[49m[43m([49m[43mpdf_folder[49m[43m)[49m

Cell [0;32mIn[4], line 5[0m, in [0;36mextract_text_from_pdf_folder[0;34m(pdf_folder_path)[0m
[1;32m      2[0m all_text [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m
[1;32m      4[0m [38;5;66;03m# Ãœber alle PDF-Dateien im Ordner iterieren[39;00m
[0;32m----> 5[0m [38;5;28;01mfor[39;00m filename [38;5;129;01min[39;00m [43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43mpdf_folder_path[49m[43m)[49m:
[1;32m      6[0m     [38;5;28;01mif[39;00m filename[38;5;241m.[39mlower()[38;5;241m.[39mendswith([38;5;124m"[39m[38;5;124m.pdf[39m[38;5;124m"[39m):
[1;32m      7[0m         file_path [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(pdf_folder_path, filename)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '...'

